{{- if .Values.oauth2.enabled }}
{{- if and .Values.oauth2.clientId .Values.oauth2.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}-oauth2-secret
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH2_CLIENT_ID: {{ .Values.oauth2.clientId }}
  OAUTH2_CLIENT_SECRET: {{ .Values.oauth2.clientSecret }}
{{- end -}}
{{- end -}}
