{{- if eq .Values.workload.kind "Deployment" -}}
{{- $fullName := include "pgadmin.fullname" . -}}
apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations: {{- include "pgadmin.tplToMap" (dict "toMap" . "context" $) | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
{{- if .Values.strategy }}
  strategy:
    {{- .Values.strategy | toYaml | nindent 4 }}
{{- end }}
  template:
{{- include "pgadmin.podTemplate" . }}
{{- end }}
