{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pgadmin.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $kubeVersion := .Capabilities.KubeVersion.Version -}}
{{- if semverCompare ">=1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare "<=1.13-0" $kubeVersion -}}
apiVersion: extensions/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and .Values.ingress.ingressClassName (semverCompare ">=1.18-0" $kubeVersion) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ tpl (.) $ | quote }}
      {{- end }}
    {{- if .secretName }}
      secretName: {{ tpl (.secretName) $ }}
    {{- end }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ tpl (.host) $ | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
          {{- if and .pathType (semverCompare ">=1.18-0" $kubeVersion) }}
            pathType: {{ .pathType }}
          {{- end }}
            backend:
            {{- if semverCompare ">=1.19-0" $kubeVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
