{{- if not .Values.existingSecret }}
{{- $fullName := include "pgadmin.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ default "SuperSecret" .Values.env.password | b64enc | quote }}
{{- end }}
{{- if .Values.serverDefinitions.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-server-definitions
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  servers.json: {{ include "pgadmin.serverDefinitions" . | b64enc | quote }}
{{- end }}
