{{- if eq .Values.workload.kind "StatefulSet" -}}
{{- $fullName := include "pgadmin.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations: {{- include "pgadmin.tplToMap" (dict "toMap" . "context" $) | nindent 4 }}
{{- end }}
spec:
  serviceName: {{ $fullName }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
{{- if .Values.strategy }}
  updateStrategy:
    {{- .Values.strategy | toYaml | nindent 4 }}
{{- end }}
  template:
{{- include "pgadmin.podTemplate" . }}
{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim) }}
  volumeClaimTemplates:
  - metadata:
      name: pgadmin-data
      labels:
        {{- include "pgadmin.selectorLabels" . | nindent 8 }}
      {{- with .Values.persistentVolume.annotations }}
      annotations: {{- include "pgadmin.tplToMap" (dict "toMap" . "context" $) | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
        {{- .Values.persistentVolume.accessModes | toYaml | nindent 8 }}
    {{- if .Values.persistentVolume.storageClass }}
    {{- if (eq "-" .Values.persistentVolume.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistentVolume.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistentVolume.size }}
{{- end }}
{{- end }}
